version: "3.7"
services:
  db:
    image: mysql
    container_name: spring-daangn-db
    env_file:
      - .env.dev
    ports:
      - "3307:3306"
    volumes:
      - ./dockerDB:/app
    restart: always
  web:
    container_name: spring-daangn-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    restart: always

