version: "3.8"
services:
  backend:
    image: "letskuku/spring-daagn-market-18th"
    ports:
      - "8080:8080"
    restart: "always"

  nginx:
    image: "letskuku/nginx"
    ports:
      - "80:80"
    restart: "always"
    depends_on:
      - "backend"