version: '3'
services:

  web:
    container_name: web
    image: yeniwithchoi/ceos-karrot
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - 8080:8080
    tty: true
    environment:
      - TZ=Asia/Seoul

  nginx:
    container_name: nginx
    image: yeniwithchoi/ceos-nginx
    ports:
      - 80:80
    depends_on:
      - web