version: "3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  web:
    container_name: web
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      mysql_host: db
    restart: always
    volumes:
      - .:/app

volumes:
  app:
  dbdata: