version: "3"

services: # 컨테이너 설정
  db:
    container_name: db  # MySQL 컨테이너의 이름 지정
    image: mysql:5.7 # 컨테이너에서 사용하는 base image 지정
    env_file: .env
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: mysql
    expose:
      - 3306
    volumes: # -v 옵션과 동일
      - dbdata:/var/lib/mysql
    ports: # -p 옵션과 동일
      - 3308:3306
    # restart: always # 컨테이너 다운 시 재시작하라는 명령어

  web:
    container_name: web
    build: . #image를 DockerFile 기반으로 사용
    ports:
      - "8080:8080"
    depends_on: # database service가 실행된 이후에 실행
      - db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      DATABASE_NAME: mysql
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: mysql
      DATABASE_PORT: 3306
      DATABASE_HOST: db
      # restart: always
    volumes:
      - .:/app

volumes:
  app:
  dbdata: