version: "3.7"
services:
  web:
    container_name: spring-daangn-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
