spring:

  profiles:
    include: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(WqAsSHd7VnF+MmgCE7fKbA4bUS2L4HSleuRxpmrwGMkhbbJGtYPT0GMXYpxZYGbSOnTkRB13+ufiqH9kazWirevA1Uk8V85a8NxRDxj8C0N10j9UtWhXO+OEtTM9ZfzZ)
    username: ENC(NywsKL218T5X7lDy4HACHg===)
    password: ENC(0t50EpHzRtQ9UgWv0xXHtd2de79nMUs4)

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      properties:
        hibernate.format_sql: true
      ddl-auto: validate

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
