spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ceos18
        username: root
        password:
#        url: ${DB_URL}
#        username: ${DB_USERNAME}
#        password: ${DB_PASSWORD}
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                database-platform: org.hibernate.dialect.MySQL8Dialect
                show_sql: true
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
jwt:
    token:
        secret: loveyoulikeicancancanbysamsmithdramamamamama

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        groups-order: DESC
        operationsSorter: method
        disable-swagger-default-url: true
        display-request-duration: true
    api-docs:
        path: /api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    paths-to-match:
        - /api/**