spring:
  jwt:
    token:
      secret: ${JWT_TOKEN}
      access-token-validity-in-seconds: 43200

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smpt:
          auth: true
          smtp:
            ssl:
              enable: true
              trust: smtp.gmail.com
        smtp:
          starttls:
            enable: true

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: debug