version: "3"

services:
  backend:
    image: nzeong/spring-boot
    container_name: backend
    hostname: backend
    env_file:
      - .env
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend
    restart: always
    image: nginx:1.15-alpine # AWS에서 이미지를 빌드한 경우 사용한 이미지의 이름으로 변경해야 합니다.
    ports:
      - "80:80"

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
