name: Deploy Development Server # 깃헙 레포지토리의 액션 탭에 노출되는 workflow의 이름으로 옵셔널한 값

## develop 브랜치에 push가 되면 실행됩니다
on:
  push:
    branches: [ "yoonsseo" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # 우리의 branch를 현재 비어있는 ubuntu에 내려받도록 함
      - name: checkout
        uses: actions/checkout@v3

      ## java 다운받기
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set APPLICATION.YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar

      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app -f Dockerfile .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/ceos18dangn:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ceos18dangn:latest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_DNS }}
          username: ubuntu
          key: ${{ secrets.PEM_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ceos18dangn:latest
            docker stop $(docker ps -a -q)
            docker-compose up -d
            docker image prune -a -f